"""Generate production-ready xahaud configuration files.

Generates xahaud.cfg and validators.txt for deploying nodes to mainnet or testnet.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import click

# Network presets with known bootstrap peers, validator keys, etc.
NETWORK_PRESETS: dict[str, dict[str, Any]] = {
    "mainnet": {
        "network_id": 21337,
        "default_peer_port": 21337,
        "ips": [
            ("bacab.alloy.ee", 21337),
            ("hubs.xahau.as16089.net", 21337),
            ("xahau-1.cabbit.tech", 21337),
            ("xahau-2.cabbit.tech", 21337),
        ],
        "validator_list_sites": [
            "https://vl.xahau.org",
        ],
        "validator_list_keys": [
            # vl.xahau.org
            "EDA46E9C39B1389894E690E58914DC1029602870370A0993E5B87C4A24EAF4A8E8",
        ],
        "import_vl_keys": [
            "ED45D1840EE724BE327ABE9146503D5848EFD5F38B6D5FEDE71E80ACCE5E6E738B",
            "ED42AEC58B701EEBB77356FFFEC26F83C1F0407263530F068C7C73D392C7E06FD1",
            "ED2677ABFFD1B33AC6FBC3062B71F1E8397C1505E1C42C64D11AD1B28FF73F4734",
        ],
        "validators": [],
    },
    "testnet": {
        "network_id": 21338,
        "default_peer_port": 21338,
        "ips": [
            ("79.110.60.121", 21338),
            ("79.110.60.122", 21338),
            ("79.110.60.124", 21338),
            ("79.110.60.125", 21338),
        ],
        "validator_list_sites": [],
        "validator_list_keys": [],
        "import_vl_keys": [
            "ED264807102805220DA0F312E71FC2C69E1552C9C5790F6C25E3729DEB573D5860",
        ],
        "validators": [
            "nHBoJCE3wPgkTcrNPMHyTJFQ2t77EyCAqcBRspFCpL6JhwCm94VZ",
            "nHUVv4g47bFMySAZFUKVaXUYEmfiUExSoY4FzwXULNwJRzju4XnQ",
            "nHBvr8avSFTz4TFxZvvi4rEJZZtyqE3J6KAAcVWVtifsE7edPM7q",
            "nHUH3Z8TRU57zetHbEPr1ynyrJhxQCwrJvNjr4j1SMjYADyW1WWe",
        ],
    },
}


@dataclass
class XahaudConfig:
    """Resolved configuration for generating xahaud config files."""

    network: str
    db_type: str = "NuDB"
    data_dir: str = "/opt/xahaud"
    peer_port: int | None = None  # None = use network default
    rpc_port: int = 5009
    ws_port: int = 6009
    node_size: str = "medium"
    log_level: str = "warning"
    online_delete: int = 512
    ledger_history: str = "256"
    peers_max: int = 21
    subscribe_url: str | None = None

    @property
    def preset(self) -> dict[str, Any]:
        return NETWORK_PRESETS[self.network]

    @property
    def effective_peer_port(self) -> int:
        if self.peer_port is not None:
            return self.peer_port
        return self.preset["default_peer_port"]


def _rpc_startup_subscribe(subscribe_url: str | None) -> str:
    """Generate subscribe line for [rpc_startup] if URL is provided."""
    if not subscribe_url:
        return ""
    import json

    cmd = json.dumps(
        {
            "command": "subscribe",
            "url": subscribe_url,
            "streams": [
                "ledger",
                "transactions",
                "validations",
                "peer_status",
                "consensus",
                "server",
            ],
        }
    )
    return f"{cmd}\n"


def generate_config(config: XahaudConfig) -> tuple[str, str]:
    """Generate xahaud.cfg and validators.txt content.

    Args:
        config: Resolved configuration values.

    Returns:
        Tuple of (xahaud_cfg_content, validators_txt_content).
    """
    preset = config.preset
    peer_port = config.effective_peer_port

    # Build [ips] section
    ips_lines = "\n".join(f"{host} {port}" for host, port in preset["ips"])

    # Build node_db section based on db_type
    if config.db_type == "RWDB":
        node_db_section = f"""type=RWDB
online_delete={config.online_delete}
advisory_delete=0"""
    else:
        node_db_section = f"""type={config.db_type}
path={config.data_dir}/db/nudb
online_delete={config.online_delete}
advisory_delete=0"""

    cfg_content = f"""# xahaud configuration - {config.network}
# Generated by x-testnet create-config

# peers_max must be > minOutCount (10) to have inbound slots available.
# See: src/ripple/peerfinder/impl/Tuning.h:59 (minOutCount = 10)
# See: src/ripple/peerfinder/impl/PeerfinderConfig.cpp:91-110
#
# Slot calculation (PeerfinderConfig.cpp:91-110):
#   outPeers = max((peers_max * 15% rounded), minOutCount)
#   inPeers  = peers_max - outPeers
#
# With peers_max=10: outPeers=10, inPeers=0 -> "slots full" on inbound!
# With peers_max=21: outPeers=10, inPeers=11 -> works correctly
[peers_max]
{config.peers_max}

[network_id]
{preset["network_id"]}

[server]
port_rpc_admin_local
port_peer
port_ws_admin_local

[port_rpc_admin_local]
port = {config.rpc_port}
ip = 127.0.0.1
admin = 127.0.0.1
protocol = http

[port_peer]
port = {peer_port}
ip = 0.0.0.0
protocol = peer

[port_ws_admin_local]
port = {config.ws_port}
ip = 127.0.0.1
admin = 127.0.0.1
protocol = ws

[node_size]
{config.node_size}

[ledger_history]
{config.ledger_history}

[node_db]
{node_db_section}

[database_path]
{config.data_dir}/db

[debug_logfile]
/var/log/xahaud/debug.log

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org

[ips]
{ips_lines}

[validators_file]
validators-xahau.txt

[rpc_startup]
{{ "command": "log_level", "severity": "{config.log_level}" }}
{_rpc_startup_subscribe(config.subscribe_url)}
[ssl_verify]
1
"""

    # Build validators.txt
    validators_parts: list[str] = [
        "# Xahau validator list configuration",
        f"# Network: {config.network}",
        "# Generated by x-testnet create-config",
        "",
    ]

    # Static validators (testnet uses these)
    if preset["validators"]:
        validators_parts.append("[validators]")
        for key in preset["validators"]:
            validators_parts.append(key)
        validators_parts.append("")

    # Validator list sites (mainnet uses these)
    if preset["validator_list_sites"]:
        validators_parts.append("[validator_list_sites]")
        for site in preset["validator_list_sites"]:
            validators_parts.append(site)
        validators_parts.append("")

    # Validator list keys
    if preset["validator_list_keys"]:
        validators_parts.append("[validator_list_keys]")
        for key in preset["validator_list_keys"]:
            validators_parts.append(key)
        validators_parts.append("")

    # Import VL keys
    if preset["import_vl_keys"]:
        validators_parts.append("[import_vl_keys]")
        for key in preset["import_vl_keys"]:
            validators_parts.append(key)
        validators_parts.append("")

    validators_content = "\n".join(validators_parts)

    return cfg_content, validators_content


def write_config(output_dir: Path, cfg_content: str, validators_content: str) -> None:
    """Write generated config files to disk.

    Args:
        output_dir: Directory to write files into.
        cfg_content: Content for xahaud.cfg.
        validators_content: Content for validators-xahau.txt.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    cfg_path = output_dir / "xahaud.cfg"
    validators_path = output_dir / "validators-xahau.txt"

    cfg_path.write_text(cfg_content)
    validators_path.write_text(validators_content)

    click.echo(f"Generated {cfg_path}")
    click.echo(f"Generated {validators_path}")


def create_config_handler(
    network: str,
    output_dir: Path,
    db_type: str = "NuDB",
    data_dir: str = "/opt/xahaud",
    node_size: str = "medium",
    log_level: str = "warning",
    online_delete: int = 512,
    ledger_history: str = "256",
    peer_port: int | None = None,
    rpc_port: int = 5009,
    ws_port: int = 6009,
    peers_max: int = 21,
    subscribe_url: str | None = None,
) -> None:
    """Generate production-ready xahaud configuration files.

    Args:
        network: Target network ("mainnet" or "testnet").
        output_dir: Directory to write generated files.
        db_type: Database backend ("NuDB" or "RWDB").
        data_dir: Data directory for db and logs.
        node_size: Node size tuning.
        log_level: Default log severity.
        online_delete: Ledgers to keep before deleting.
        ledger_history: Ledger history depth.
        peer_port: Override peer port (default: network-specific).
        rpc_port: RPC port.
        ws_port: WebSocket port.
        peers_max: Max peer connections.
        subscribe_url: URL for auto-subscribe on startup.
    """
    config = XahaudConfig(
        network=network,
        db_type=db_type,
        data_dir=data_dir,
        peer_port=peer_port,
        rpc_port=rpc_port,
        ws_port=ws_port,
        node_size=node_size,
        log_level=log_level,
        online_delete=online_delete,
        ledger_history=ledger_history,
        peers_max=peers_max,
        subscribe_url=subscribe_url,
    )

    cfg_content, validators_content = generate_config(config)
    write_config(output_dir, cfg_content, validators_content)
